routes/index.py
import uuid
import os
import hashlib
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
)

from models.user import User
from models.topic import Topic
from models.reply import Reply
from routes import login_required, login_required_id
from utils import log


main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.one(id=uid)
    return u

def hash_pass(password, salt='$!@><?>HUI&DWQa`'):
    str = hashlib.sha256(password.encode('ascii')).hexdigest()
    s = str + salt
    result = hashlib.sha256(s.encode('ascii')).hexdigest()
    return  result


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    # form = request.args
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login user <{}>'.format(u))
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        print('session是什么：', session)
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('gua_topic.index'))


@main.route('/profile')
@login_required
def profile():
    u = current_user()
    t = Topic.all(user_id=u.id)
    t.reverse()
    r = Reply.all(user_id=u.id)
    r.reverse()
    print('t是什么：', t)
    print('r是什么:', r)
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u, topic=t, reply=r)


@main.route('/user/<int:id>')
@login_required_id
def user_set(*args, **kwargs):
    id = kwargs['id']
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('set.html', user=u)

@main.route('/user/update', methods=['POST'])
def user_update():
    u = current_user()
    form = request.form.to_dict()
    print('form:', form, u)
    if 'old_pass' in form and u.password == hash_pass(form['old_pass']):
        form.pop('old_pass')
        form['password'] = hash_pass(form['password'])
        User.update(u.id, **form)
    else:
        User.update(u.id, **form)
    return redirect(url_for('.user_set', id=u.id))


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file = request.files['avatar']
    # ../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.profile'))

@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:2000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    return send_from_directory('images', filename)


def not_found(e):
    return render_template('404.html')


# def blueprint():
#     main = Blueprint('index', __name__)
#     main.route("/")(index)
#     main.route("/register", methods=['POST'])(register)
#     main.route("/login", methods=['POST'])(login)
#     main.route('/profile')(profile)
#     main.route('/user/<int:id>')(user_detail)
#
#     return main

routes/message.py
from flask_mail import Message, Mail
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.message import Messages
# from config import admin_mail

main = Blueprint('mail', __name__)
mail = Mail()


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    form['receiver_id'] = int(form['receiver_id'])
    u = current_user()
    form['sender_id'] = u.id

    # 发邮件
    # r = User.one(id=form['receiver_id'])
    # m = Message(
    #     subject=form['title'],
    #     body=form['content'],
    #     sender=admin_mail,
    #     recipients=[r.email]
    # )
    # mail.send(m)

    m = Messages.new(form)
    return redirect(url_for('.index'))


@main.route('/')
def index():
    u = current_user()

    sent_mail = Messages.all(sender_id=u.id)
    received_mail = Messages.all(receiver_id=u.id)

    t = render_template(
        'mail/index.html',
        send=sent_mail,
        received=received_mail,
        user=u,
    )
    return t


@main.route('/view/<int:id>')
def view(id):
    mail = Messages.one(id=id)
    u = current_user()
    # if u.id == mail.receiver_id or u.id == mail.sender_id:
    if u.id in [mail.receiver_id, mail.sender_id]:
        return render_template('mail/detail.html', mail=mail)
    else:
        return redirect(url_for('.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user, login_required, csrf_required, new_csrf_token

from models.topic import Topic


main = Blueprint('gua_topic', __name__)


@main.route("/")
@login_required
def index():
    u = current_user()
    print('u shenme :', u)
    ms = Topic.all()
    token = new_csrf_token()
    return render_template("topic/index.html", ms=ms, user=u, token=token)


@main.route('/<int:id>')
# /topic/1
# @main.route('/')
# /topic?id=1
def detail(id):
    # id = int(request.args['id'])
    # http://localhost:3000/topic/1
    u = current_user()
    m = Topic.get(id)

    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u)

@main.route("/delete")
@csrf_required
@login_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    u = current_user()
    token = new_csrf_token()
    return render_template("topic/new.html", user=u, token=token)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户登陆</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('index.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
    <form class="form-horizontal" method="post" action="{{ url_for('index.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="登录">
        </div>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="/static/css/index.min.23a5b1ca.min.css">
    <title>{{user.username}} 的个人主页</title>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
         <div class="container">
              <a class="brand" href="{{ url_for('gua_topic.index') }}">
                  <!--<img src="/static/css/cnodejs_light.svg">-->
              </a>

              <form id="search_form" class="navbar-search" action="">
                   <input type="text" id="q" name="q" class="search-query span3" value="">
              </form>
              <ul class="nav pull-right">
                   <li><a href="{{ url_for('gua_topic.index') }}">首页</a></li>
                   <li><a href="">未读消息</a></li>
                   <li><a href="{{ url_for('mail.index') }}">邮箱</a></li>
                   <li><a href="{{ url_for('index.user_set', id=user.id) }}">设置</a></li>
                   <li><a href="" data-method="post" rel="nofollow">退出</a></li>
              </ul>
              <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
              </a>
         </div>
     </div>
</div>
    <div id="main">
         <div id="content">
              <div class="panel">
                   <div class="header">
                        <ul class="breadcrumb">
                             <li><a href="{{ url_for('gua_topic.index') }}">主页</a><span class="divider">/</span></li>
                        </ul>
                   </div>
                   <div class="inner userinfo">
                        <div class="user_big_avatar">
                             <img src="{{user.image}}" class="user_avatar">
                        </div>
                        <a class="dark" href="{{ url_for('index.profile') }}">{{user.username}}</a>
                        <br/>
                        <br/>
                        <div>
                             <p class="col_fade" data-created_time="{{ user.created_time }}"></p>
                        </div>
                   </div>
              </div>

              <div class="panel">
                   <div class="header">
                        <span class="col_fade">最近创建的话题</span>
                   </div>
                   {% for t in topic %}
                   <div class="cell">

                        <a class="user_avatar pull-left">
                            <img src="{{user.image}}">
                        </a>

                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">{{t.replies() | count }}</span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title="点击数">{{t.views}}</span>
                        </span>

                        <span class="last_time pull-right">
                             <img class="user_small_avatar" src="{{user.image}}">
                            <span class="last_active_time" data-created_time="{{ t.created_time }}"></span>
                        </span>

                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('gua_topic.detail', id=t.id) }}">
                                 {{t.title}}
                            </a>
                        </div>

                   </div>
                   {% endfor %}
              </div>

              <div class="panel">
                   <div class="header">
                        <span class="col_fade">最近参与的话题</span>
                   </div>
                   {% for r in reply %}
                   <div class="cell">

                        <a class="user_avatar pull-left">
                             <img src="{{user.image}}">
                        </a>

                        <span class="reply_count pull-left">
                             <span class="count_of_replies" title="回复数">{{r.find_topic().replies() | count}}</span>
                             <span class="count_seperator">/</span>
                             <span class="count_of_visits" title="点击数">{{r.find_topic().views}}</span>
                        </span>


                        <a class="last_time pull-right" href="">
                             <img class="user_small_avatar" src="{{user.image}}">
                             <span class="last_active_time last_active_timer" data-created_time="{{ r.created_time }}"></span>
                         </a>

                        <div class="topic_title_wrapper">

                             <span class="put_top">置顶</span>
                             <a class="topic_title" href="{{ url_for('gua_topic.detail', id=r.find_topic().id) }}">
                                 {{r.find_topic().title}}
                             </a>
                        </div>
                    </div>
                   {% endfor %}
              </div>

         </div>
    </div>
    <script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var registerTimer = function () {
            var t = e('.col_fade')
            var time = Number(t.dataset.created_time)
            var now = Math.floor(new Date() / 1000)
            var delta = Math.floor((now - time) / 3600)
            var s = `注册时间 ${delta} 小时前`
            t.innerText = s
        }
        var startTimer = function() {
            var ts = es('.last_active_time')
            for (var i = 0; i < ts.length; i++) {
                 var t = ts[i]
                 var time = Number(t.dataset.created_time)
                 var now = Math.floor(new Date() / 1000)
                 var delta = Math.floor((now - time) / 3600)
                 var s = `${delta} 小时前`
                 t.innerText = s
            }
        }

        var statTime = function() {
            var ts = es('.last_active_timer')
            for (var i = 0; i < ts.length; i++) {
                 var t = ts[i]
                 var time = Number(t.dataset.created_time)
                 var now = Math.floor(new Date() / 1000)
                 var delta = Math.floor((now - time) / 3600)
                 var s = `${delta} 小时前`
                 t.innerText = s
            }
        }

        var __main = function () {
            registerTimer()
            startTimer()
            statTime()
        }

        __main()

    </script>
</body></html>

templates/set.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="/static/css/index.min.23a5b1ca.min.css" media="all">
    <title>个人主页设置</title>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
         <div class="container">
              <a class="brand" href="{{ url_for('gua_topic.index') }}">
                   <!--<img src="/static/css/cnodejs_light.svg">-->
              </a>

              <form id="search_form" class="navbar-search" action="">
                   <input type="text" id="q" name="q" class="search-query span3" value="">
              </form>
              <ul class="nav pull-right">
                   <li><a href="{{ url_for('gua_topic.index') }}">首页</a></li>
                   <li><a href="">未读消息</a></li>
                   <li><a href="{{ url_for('mail.index') }}">邮箱</a></li>
                   <li><a href="{{ url_for('index.user_set', id=user.id) }}">设置</a></li>
                   <li><a href="" data-method="post" rel="nofollow">退出</a></li>
              </ul>
              <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
              </a>
         </div>
     </div>
</div>

<div id="main">
    <div id="sidebar">

         <div class="panel">
              <div class="header">
                   <span class="col_fade">个人信息</span>
              </div>
              <div class="inner">
                   <div class="user_card">
                        <div>
                             <a class="user_avatar" href="{{ url_for('index.profile') }}">
                                  <img src="{{user.image}}" title="{{user.username}}">
                             </a>
                             <span class="user_name"><a class="dark" href="{{ url_for('index.profile') }}">{{user.username}}</a></span>

                             <div class="board clearfix"></div>
                             <div class="space clearfix"></div>
                             <span class="signature">{{user.autograph}}</span>
                        </div>
                   </div>
              </div>
         </div>

         <div class="panel">
              <div class="inner">
                   <a href="{{ url_for('gua_topic.new') }}" id="create_topic_btn"><span class="span-success">发布话题</span></a>
              </div>
         </div>

    </div>

    <div id="content">
         <div class="panel">
              <div class="header">
                   <ul class="breadcrumb">
                        <li><a href="https://cnodejs.org/">主页</a><span class="divider">/</span></li>
                        <li class="active">设置</li>
                   </ul>
              </div>
              <div class="inner">
                   <form id="setting_form" class="form-horizontal" action="{{ url_for('index.user_update') }}" method="post">
                        <div class="control-group">
                             <label class="control-label">用户名</label>
                             <div class="controls">
                                  <input class="input-xlarge readonly" name="username" size="30" type="text" value="{{user.username}}">
                             </div>
                        </div>

                        <div class="control-group">
                             <label class="control-label">个性签名</label>

                             <div class="controls">
                                  <textarea class="input-xlarge" name="autograph"></textarea>
                             </div>
                        </div>

                        <div class="form-actions">
                             <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                        </div>
                   </form>
              </div>
         </div>

        <div class="panel">
             <div class="header">
                  <span class="col_fade">更改密码</span>
             </div>
             <div class="inner">
                  <form id="change_pass_form" class="form-horizontal" action="{{ url_for('index.user_update') }}" method="post">
                       <div class="control-group">
                            <label class="control-label">当前密码</label>

                            <div class="controls">
                                 <input class="input-xlarge" type="password" name="old_pass" size="30">
                            </div>
                       </div>
                       <div class="control-group">
                            <label class="control-label">新密码</label>

                            <div class="controls">
                                 <input class="input-xlarge" type="password" name="password" size="30">
                            </div>
                       </div>

                       <div class="form-actions">
                            <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
                       </div>
                  </form>
             </div>
        </div>
         <div class="panel">
             <div class="header">
                  <span class="col_fade">上传头像</span>
             </div>
             <div class="inner">
                  <form method="post" action="{{ url_for('.avatar_add')}}" enctype="multipart/form-data">
                       <input type="file" name="avatar">
                       <button type="submit">上传头像</button>
                  </form>
             </div>
        </div>

    </div>

</div>

<div id="footer" style="background:#3C3C3C">
    <div id="footer_main">
         <div class="links" style="color:white">

              <strong></strong><em><a class="dark" href="">KBC</a>
              |
              <a class="dark" href="https://www.kuaibiancheng.com/">网址: https://www.kuaibiancheng.com/</a></em></strong>
         </div>

         <div class="col_fade"></div>
     </div>
</div>

</body></html>