models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models import Model
from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)

    @classmethod
    def add(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m


    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

routes/index.py
import uuid
import os
import hashlib
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
)

from models.user import User
from models.topic import Topic
from models.reply import Reply
from routes import login_required, login_required_id
from utils import log


main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.one(id=uid)
    return u

def hash_pass(password, salt='$!@><?>HUI&DWQa`'):
    str = hashlib.sha256(password.encode('ascii')).hexdigest()
    s = str + salt
    result = hashlib.sha256(s.encode('ascii')).hexdigest()
    return  result


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    # form = request.args
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login user <{}>'.format(u))
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        print('session是什么：', session)
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('gua_topic.index'))


@main.route('/profile')
@login_required
def profile():
    u = current_user()
    t = Topic.all(user_id=u.id)
    t.reverse()
    r = Reply.all(user_id=u.id)
    r.reverse()
    print('t是什么：', t)
    print('r是什么:', r)
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u, topic=t, reply=r)


@main.route('/user/<int:id>')
@login_required_id
def user_set(*args, **kwargs):
    id = kwargs['id']
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('set.html', user=u)

@main.route('/user/update', methods=['POST'])
def user_update():
    u = current_user()
    form = request.form.to_dict()
    print('form:', form, u)
    if 'old_pass' in form and u.password == hash_pass(form['old_pass']):
        form.pop('old_pass')
        form['password'] = hash_pass(form['password'])
        User.update(u.id, **form)
    else:
        User.update(u.id, **form)
    return redirect(url_for('.user_set', id=u.id))


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file = request.files['avatar']
    # ../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.profile'))

@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:2000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    return send_from_directory('images', filename)


def not_found(e):
    return render_template('404.html')


# def blueprint():
#     main = Blueprint('index', __name__)
#     main.route("/")(index)
#     main.route("/register", methods=['POST'])(register)
#     main.route("/login", methods=['POST'])(login)
#     main.route('/profile')(profile)
#     main.route('/user/<int:id>')(user_detail)
#
#     return main

routes/message.py
from flask_mail import Message, Mail
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.message import Messages
# from config import admin_mail

main = Blueprint('mail', __name__)
mail = Mail()


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    form['receiver_id'] = int(form['receiver_id'])
    u = current_user()
    form['sender_id'] = u.id

    # 发邮件
    # r = User.one(id=form['receiver_id'])
    # m = Message(
    #     subject=form['title'],
    #     body=form['content'],
    #     sender=admin_mail,
    #     recipients=[r.email]
    # )
    # mail.send(m)

    m = Messages.new(form)
    return redirect(url_for('.index'))


@main.route('/')
def index():
    u = current_user()

    sent_mail = Messages.all(sender_id=u.id)
    received_mail = Messages.all(receiver_id=u.id)

    t = render_template(
        'mail/index.html',
        send=sent_mail,
        received=received_mail,
        user=u,
    )
    return t


@main.route('/view/<int:id>')
def view(id):
    mail = Messages.one(id=id)
    u = current_user()
    # if u.id == mail.receiver_id or u.id == mail.sender_id:
    if u.id in [mail.receiver_id, mail.sender_id]:
        return render_template('mail/detail.html', mail=mail)
    else:
        return redirect(url_for('.index'))

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.reply import Reply
from models.user import User
from models.message import Messages

def users_from_content(content):
    parts = content.split()
    users = []
    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            if u is not None:
                users.append(u)
    return users

def send_mails(sender, receivers, content):
    for r in receivers:
        form = dict(
            title='你被 {} AT 了'.format(sender.username),
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )
        Messages.new(form)

main = Blueprint('gua_reply', __name__)

@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()

    content = form['content']
    users = users_from_content(content)
    send_mails(u, users, content)

    print('DEBUG', form)
    m = Reply.add(form, user_id=u.id)
    return redirect(url_for('gua_topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user, login_required, csrf_required, new_csrf_token

from models.topic import Topic


main = Blueprint('gua_topic', __name__)


@main.route("/")
@login_required
def index():
    u = current_user()
    print('u shenme :', u)
    ms = Topic.all()
    token = new_csrf_token()
    return render_template("topic/index.html", ms=ms, user=u, token=token)


@main.route('/<int:id>')
# /topic/1
# @main.route('/')
# /topic?id=1
def detail(id):
    # id = int(request.args['id'])
    # http://localhost:3000/topic/1
    u = current_user()
    m = Topic.get(id)

    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u)

@main.route("/delete")
@csrf_required
@login_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    m = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    u = current_user()
    token = new_csrf_token()
    return render_template("topic/new.html", user=u, token=token)

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ topic.title }}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="//cdn.bootcss.com/prism/1.8.0/themes/prism.css" rel="stylesheet">
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
         <div class="container">
              <a class="brand" href="{{ url_for('gua_topic.index') }}">
                  <!--<img src="/static/css/cnodejs_light.svg">-->
              </a>

              <form id="search_form" class="navbar-search" action="">
                   <input type="text" id="q" name="q" class="search-query span3" value="">
              </form>
              <ul class="nav pull-right">
                   <li><a href="{{ url_for('gua_topic.index') }}">首页</a></li>
                   <li><a href="">未读消息</a></li>
                   <li><a href="{{ url_for('mail.index') }}">邮箱</a></li>
                   <li><a href="{{ url_for('index.user_set', id=user.id) }}">设置</a></li>
                   <li><a href="" data-method="post" rel="nofollow">退出</a></li>
              </ul>
              <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
              </a>
         </div>
     </div>
</div>
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.created_time | format_time }}
            </span>
                    <span>
                        作者 <a href="{{ url_for('index.profile') }}">{{ topic.user().username }}</a>
                {# 作者 {{ User.one(id=topic.user_id).username }} #}
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        {% set u = r.user() %}
        <div class='cell reply_area reply_item'>
            <div class='user_info'>
                <a class='dark reply_author'>
                    {{ u.username }}
                </a>
                <a class="reply_time">
                    {{ loop.index }}楼 / {{ loop.length }}楼 •
                    <span class="gua-time" data-created_time="{{ r.created_time }}"></span>
                </a>
            </div>
            <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">{{ r.content }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div>
        <form action="{{ url_for('gua_reply.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea name="content"></textarea>
            <button>添加回复</button>
        </form>
    </div>
</div>
<div id="footer" style="background:#3C3C3C">
    <div id="footer_main">
         <div class="links" style="color:white">

              <strong></strong><em><a class="dark" href="">KBC</a>
              |
              <a class="dark" href="https://www.kuaibiancheng.com/">网址: https://www.kuaibiancheng.com/</a></em></strong>
         </div>

         <div class="col_fade"></div>
     </div>
</div>
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var registerTimer = function () {
        setInterval(function () {
            var times = es('.gua-time')
            for (var i = 0; i < times.length; i++) {
                var t = times[i]
                var time = Number(t.dataset.created_time)
                var now = Math.floor(new Date() / 1000)
                var delta = now - time
                var s = `${delta} 秒前`
                t.innerText = s
            }
        }, 1000)
    }

    var __main = function () {
        markContents()
        highlight()
        registerTimer()
    }

    __main()

</script>
</body>
</html>

templates/topic/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{user.username}}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <style>
        .user_head {
            display: inline-block;
            height: 50px;
            width: 100px;
        }
        .user_head:after{
            content:'';
            width:0;
            height:100%;
            display:inline-block;
            vertical-align:middle;
        }
        .sssss {
            display: inline-block;
            vertical-align: middle;
        }
        .input_active {
            display: none;
        }
    </style>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
         <div class="container">
              <a class="brand" href="{{ url_for('gua_topic.index') }}">
                  <!--<img src="/static/css/cnodejs_light.svg">-->
              </a>

              <form id="search_form" class="navbar-search" action="">
                   <input type="text" id="q" name="q" class="search-query span3" value="">
              </form>
              <ul class="nav pull-right">
                   <li><a href="{{ url_for('gua_topic.index') }}">首页</a></li>
                   <li><a href="">未读消息</a></li>
                   <li><a href="{{ url_for('mail.index') }}">邮箱</a></li>
                   <li><a href="{{ url_for('index.user_set', id=user.id) }}">设置</a></li>
                   <li><a href="" data-method="post" rel="nofollow">退出</a></li>
              </ul>
              <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
              </a>
         </div>
     </div>
</div>
    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                     <span class="col_fade">个人信息</span>
                </div>
                <div class="inner">
                     <div class="user_card">
                         <div>
                             <div class="user_head">
                                 <div class="sssss">
                                     <a class="user_avatar"  href="{{ url_for('index.profile') }}">
                                         <img src="{{ user.image }}" title="{{user.username}}">
                                     </a>
                                 </div>
                                 <div class="sssss">
                                     <span class="user_name"><a class="dark" href="{{ url_for('index.profile') }}">{{user.username}}</a></span>
                                 </div>
                             </div>
                             <div class="board clearfix">
                                 <button class="button_t">上传头像</button>
                                 <form class="input_active ss" method="post" action="{{ url_for('index.avatar_add')}}" enctype="multipart/form-data">
                                     <input type="file" name="avatar">
                                     <button class="button_tt" type="submit">上传头像</button>
                                 </form>
                             </div>
                             <div class="space clearfix">
                             </div>
                             <span class="signature">{{user.autograph}}</span>
                         </div>
                     </div>
                </div>
            </div>
            <div class="panel">
                <div class="inner">
                    <a href="{{ url_for('gua_topic.new') }}" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                        <div class="cell">
                            <div class="topic_title_wrapper">
                                <a class="topic_title" href="{{ url_for('gua_topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>
                                <span>{{ t.replies() | count }} / {{ t.views }}</span>
                                <a class="topic_title" href="{{ url_for('gua_topic.delete', id=t.id, token=token) }}">
                                     删除
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var e = function(selector) {
            return document.querySelector(selector)
        }
        var t = function() {
            var s = e('.button_t')
            s.addEventListener('click', function(event){
                var self = e('.ss')
                self.classList.toggle('input_active')
                s.classList.toggle('input_active')
            })
            var n = e('.button_tt')
            n.addEventListener('click', function(event){
                var self = e('.ss')
                self.classList.toggle('input_active')
            })
        }
        var __main = function() {
            t()
        }
        __main()
    </script>
</body>
<!--<script src="/static/js/test.js"></script>-->
</html>

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>publish an article</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
<body>
<div class="navbar">
    <div class="navbar-inner">
         <div class="container">
              <a class="brand" href="{{ url_for('gua_topic.index') }}">
                  <!--<img src="/static/css/cnodejs_light.svg">-->
              </a>

              <form id="search_form" class="navbar-search" action="">
                   <input type="text" id="q" name="q" class="search-query span3" value="">
              </form>
              <ul class="nav pull-right">
                   <li><a href="{{ url_for('gua_topic.index') }}">首页</a></li>
                   <li><a href="">未读消息</a></li>
                   <!--<li><a href="">新手入门</a></li>-->
                   <!--<li><a href="">API</a></li>-->
                   <li><a href="{{ url_for('.index') }}">邮箱</a></li>
                   <li><a href="{{ url_for('index.user_set', id=user.id) }}">设置</a></li>
                   <li><a href="" data-method="post" rel="nofollow">退出</a></li>
              </ul>
              <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
              </a>
         </div>
     </div>
</div>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add', token=token ) }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                                <div class='markdown_in_editor'>
                                     <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                     <div class='editor_buttons'>
                                          <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                     </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div id="footer" style="background:#3C3C3C">
    <div id="footer_main">
         <div class="links" style="color:white">

              <strong></strong><em><a class="dark" href="">KBC</a>
              |
              <a class="dark" href="https://www.kuaibiancheng.com/">网址: https://www.kuaibiancheng.com/</a></em></strong>
         </div>

         <div class="col_fade"></div>
     </div>
</div>
</body>
<script>
  (sfunction () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</html>